/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
static yyconst short int yy_accept[337] =
    {   0,
       66,   66,   72,   71,   66,   29,   71,   71,   28,   36,
       25,   26,   33,   31,   27,   32,   71,   34,   69,   54,
       38,   37,   39,   16,   70,   70,   70,   70,   70,   70,
       21,   22,   35,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   23,   24,   66,   42,
        0,   67,    0,   43,    0,    0,   44,   69,   68,    0,
       64,   30,   40,   41,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   47,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,    0,    0,    0,    0,   64,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   70,   70,    8,
       70,   70,   70,   70,    7,   70,    6,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,    0,   68,   65,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   49,   48,   63,   70,   70,   70,   70,   70,   14,
       70,   13,   70,   70,   70,   70,   46,   70,   45,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   53,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       62,   70,   70,   70,   70,   70,    0,   70,    0,    0,
        0,   70,   70,   70,    0,    0,   70,   70,   70,   70,
       70,   70,    0,   70,   70,   70,    0,   70,    0,    0,
       61,    0,   70,   70,   70,    0,    0,   18,   19,   17,
       20,   70,   70,    0,   70,   70,   70,    0,   70,    0,
       60,    0,   70,   52,   70,    0,    0,   70,    0,   56,
       12,    0,   15,    0,    1,    0,    0,    0,    0,    0,
       70,   70,    0,    0,   70,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   70,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   70,    0,    0,

        0,    0,    0,   58,   51,    2,    0,    0,    0,    0,
       70,   57,   59,    0,    0,    0,    5,    0,    0,   10,
       70,    0,    0,    0,    4,    0,   70,    0,    9,   50,
        0,   55,    0,    3,   11,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,    1,   21,
       22,   23,    1,   24,   25,   26,   25,   27,   28,   29,
       25,   25,   30,   25,   25,   31,   32,   25,   33,   25,
       25,   25,   34,   25,   25,   25,   25,   25,   25,   25,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   25,   49,   50,   51,   52,
       53,   54,   25,   55,   56,   57,   58,   59,   60,   25,
       61,   25,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    4,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1
    } ;

static yyconst short int yy_base[342] =
    {   0,
        0,    0,  512,  513,  509,  513,  488,   59,  513,  513,
      513,  513,  513,   53,  513,   59,   62,   71,   71,  513,
       53,  513,  487,  513,  469,   52,   27,   45,   55,   44,
      513,  513,  513,   53,   60,   61,   63,   67,   64,   76,
       66,   73,   81,   83,   85,   90,  513,  513,  505,  513,
      118,  513,  503,  513,  120,  126,  513,  131,  138,  149,
        0,  513,  513,  513,  466,    0,   92,  101,  119,  120,
      123,  465,  125,  108,  128,  129,  130,  131,  135,  133,
      137,  140,  464,  138,  145,  147,  150,  151,  157,  159,
      162,  163,  164,  205,  196,  217,  218,    0,    0,  199,

      188,  200,  172,  192,  452,  193,  194,  196,  462,  461,
      460,  165,  198,  197,  459,  166,  458,  457,  456,  204,
      206,  207,  205,  208,  455,  454,  211,  249,  252,  245,
      219,  222,  224,  225,  234,  439,  235,  236,  233,  438,
      442,  450,  449,  448,  237,  433,  432,  239,  244,  445,
      249,  444,  251,  429,  428,  441,  440,  252,  439,  254,
      256,  425,  437,  255,  436,  429,  416,  257,  427,  426,
      260,  258,  431,  264,  424,  423,  269,  266,  270,  428,
      420,  405,  425,  403,  423,    0,  276,  422,  421,  305,
      277,  417,  419,  418,  417,  400,  404,  401,  397,  279,

      412,  397,  410,  400,  394,  398,  394,  281,  393,  306,
      387,  403,  392,  392,  388,  387,  380,  379,  378,  377,
      394,  387,  391,  373,  384,  371,  366,  287,  365,  408,
      513,  385,  366,  365,  364,  359,  358,    0,    0,    0,
        0,  365,  378,  360,  368,  375,  366,  370,  288,  369,
      513,  304,  357,    0,  365,  366,  365,  361,  354,  513,
        0,  353,    0,  350,  363,  348,  367,  351,  358,  340,
      357,  340,  341,  340,  353,  330,  329,  346,  345,  372,
      345,  328,  329,  328,  342,  338,  337,  328,  336,  335,
      332,  331,  327,  358,  325,  323,  326,  312,  324,  323,

      305,  312,  309,  513,  513,  513,  302,  333,  295,  289,
      297,  513,  513,  301,  299,  298,  513,  293,  293,  513,
      280,  277,  284,  205,  513,  201,  121,   92,  513,  513,
       78,    0,   49,  513,  513,  513,  350,  352,  356,  360,
       66
    } ;

static yyconst short int yy_def[342] =
    {   0,
      336,    1,  336,  336,  336,  336,  336,  337,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  338,  338,  338,  338,  338,  338,
      336,  336,  336,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  336,  336,  336,  336,
      337,  336,  337,  336,  336,  336,  336,  336,  336,  339,
      340,  336,  336,  336,  338,  341,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  336,  339,  339,  339,  340,  341,  338,

      338,  338,  338,  338,  341,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  336,  336,  339,
      338,  338,  338,  338,  338,  341,  338,  338,  338,  341,
      341,  338,  338,  338,  338,  341,  341,  338,  338,  338,
      338,  338,  338,  341,  341,  338,  338,  338,  338,  338,
      338,  341,  338,  338,  338,  341,  341,  338,  341,  341,
      338,  338,  338,  338,  341,  341,  341,  338,  338,  338,
      341,  341,  338,  341,  341,  341,  338,  341,  341,  338,
      338,  341,  338,  341,  341,  341,  341,  341,  341,  338,

      338,  341,  341,  341,  341,  341,  336,  338,  336,  336,
      336,  338,  341,  341,  336,  336,  341,  341,  341,  341,
      338,  341,  336,  341,  341,  341,  336,  338,  336,  336,
      336,  336,  341,  341,  341,  336,  336,  341,  341,  341,
      341,  341,  341,  336,  341,  341,  341,  336,  338,  336,
      336,  336,  341,  341,  341,  336,  336,  341,  336,  336,
      341,  336,  341,  336,  338,  336,  336,  336,  336,  336,
      341,  341,  336,  336,  341,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  341,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  341,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      341,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      341,  336,  336,  336,  336,  336,  341,  336,  336,  336,
      336,  341,  336,  336,  336,    0,  336,  336,  336,  336,
      336
    } ;

static yyconst short int yy_nxt[577] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   19,   19,   20,
       21,   22,   23,   24,   25,   25,   26,   25,   27,   28,
       25,   25,   29,   30,   31,    4,   32,   33,    4,   34,
       35,   36,   25,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   25,   25,   25,   45,   46,   25,   25,   25,
       25,   47,   48,   52,   54,   66,   62,   55,   99,   56,
       56,   56,   57,   55,   63,   58,   58,   58,   59,   59,
       59,   60,   66,   66,   68,   55,   61,   58,   58,   58,
       66,   66,  335,   66,   53,   67,   69,   70,   66,   66,

       71,   66,   66,   73,   66,   66,   80,   82,   72,   85,
       75,   66,   79,   76,   66,   77,   81,   74,   78,   66,
       83,   66,   52,   66,  334,   86,   89,   84,   66,   92,
       66,   90,   91,  100,  333,   88,   59,   59,   59,   66,
       55,   87,   56,   56,   56,   55,   66,   58,   58,   58,
       93,   96,  101,   53,   59,   59,   59,   66,   66,   97,
      102,   66,  103,   66,  107,   94,   66,   66,   66,   66,
      106,   66,  332,   66,  114,   66,   66,  104,   66,  116,
      108,   94,  112,   66,  109,   66,  110,  111,   66,   66,
      113,  120,  119,  115,  117,   66,  122,   66,   96,  134,

       66,   66,   66,   66,   66,  118,   97,  121,  145,  142,
       66,  123,  124,  125,  126,  331,  128,  127,  128,   96,
       96,  129,  129,  129,  131,  133,   66,   97,   97,  132,
       66,   66,   66,  130,   66,   66,   66,   66,   66,  135,
      137,  143,   66,   66,   66,   66,   66,   96,  330,   66,
      138,  139,  149,  144,  156,   97,  148,   66,  150,  151,
       66,  153,   66,   66,  152,  129,  129,  129,  129,  129,
      129,   66,   66,   66,   66,   66,  165,   66,  158,  157,
      168,  171,   66,  160,  159,  161,  163,   66,  164,   66,
       66,  172,   66,   66,   66,   66,   66,  179,   66,  178,

      174,  180,   66,  190,   66,  173,  183,  193,   66,  191,
      196,  187,  211,  197,   66,   66,  198,   66,  200,   66,
      208,  201,  212,  230,  199,   66,   66,  329,  228,  328,
      221,  265,  327,  267,  268,  269,  249,  270,  326,  325,
      324,  323,  322,   66,  321,  320,  319,  318,  317,  231,
       51,   51,   51,   51,   65,   65,   95,   95,   95,   95,
       98,  316,   98,   98,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,

      279,   66,  278,  277,  276,  275,  274,  273,  272,  271,
      266,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  229,  227,  226,  225,  224,  223,  222,
       66,  220,  219,  218,  217,  216,  215,  214,  213,  210,
      209,  207,  206,  205,  204,  203,  202,  195,  194,  192,
      189,  188,  186,  185,  184,  182,  181,   66,   66,  177,
      176,  175,   66,   66,  170,  169,   66,   66,   66,  167,
      166,  162,  155,  154,  147,  146,   66,   66,  141,   66,

      140,  136,   66,  105,   66,  336,   49,   66,   64,   50,
       49,  336,    3,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336
    } ;

static yyconst short int yy_chk[577] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,   14,   27,   21,   14,  341,   14,
       14,   14,   16,   16,   21,   16,   16,   16,   17,   17,
       17,   18,   30,   28,   27,   19,   18,   19,   19,   19,
       26,   34,  333,   29,    8,   26,   28,   29,   35,   36,

       30,   37,   39,   35,   41,   38,   38,   39,   34,   41,
       36,   42,   37,   36,   40,   36,   38,   35,   36,   43,
       40,   44,   51,   45,  331,   42,   45,   40,   46,   46,
       67,   45,   45,   67,  328,   44,   55,   55,   55,   68,
       56,   43,   56,   56,   56,   58,   74,   58,   58,   58,
       46,   60,   68,   51,   59,   59,   59,   69,   70,   60,
       69,   71,   70,   73,   74,   59,   75,   76,   77,   78,
       73,   80,  327,   79,   80,   81,   84,   71,   82,   82,
       75,   59,   79,   85,   76,   86,   77,   78,   87,   88,
       79,   87,   86,   81,   84,   89,   89,   90,   95,  103,

       91,   92,   93,  112,  116,   85,   95,   88,  116,  112,
      103,   90,   91,   91,   92,  326,   94,   93,   94,   96,
       97,   94,   94,   94,  100,  102,  101,   96,   97,  101,
      104,  106,  107,   97,  108,  114,  113,  100,  102,  104,
      106,  113,  120,  123,  121,  122,  124,  130,  324,  127,
      107,  108,  121,  114,  127,  130,  120,  131,  122,  123,
      132,  124,  133,  134,  123,  128,  128,  128,  129,  129,
      129,  139,  135,  137,  138,  145,  139,  148,  132,  131,
      145,  148,  149,  134,  133,  135,  137,  151,  138,  153,
      158,  149,  160,  164,  161,  168,  172,  160,  171,  158,

      153,  161,  174,  171,  178,  151,  164,  174,  179,  172,
      177,  168,  190,  177,  187,  191,  177,  200,  178,  208,
      187,  179,  191,  210,  177,  228,  249,  323,  208,  322,
      200,  249,  321,  252,  252,  252,  228,  252,  319,  318,
      316,  315,  314,  190,  311,  310,  309,  308,  307,  210,
      337,  337,  337,  337,  338,  338,  339,  339,  339,  339,
      340,  303,  340,  340,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,

      266,  265,  264,  262,  259,  258,  257,  256,  255,  253,
      250,  248,  247,  246,  245,  244,  243,  242,  237,  236,
      235,  234,  233,  232,  230,  229,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  209,  207,  206,  205,  204,  203,  202,
      201,  199,  198,  197,  196,  195,  194,  193,  192,  189,
      188,  185,  184,  183,  182,  181,  180,  176,  175,  173,
      170,  169,  167,  166,  165,  163,  162,  159,  157,  156,
      155,  154,  152,  150,  147,  146,  144,  143,  142,  141,
      140,  136,  126,  125,  119,  118,  117,  115,  111,  110,

      109,  105,   83,   72,   65,   53,   49,   25,   23,    7,
        5,    3,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "test.l"
#define INITIAL 0
#line 2 "test.l"
#include "test.tab.h"
#include<stdio.h>
#include<string.h>
#include<stdlib.h>
int varindex(char *var);
extern int yylex();
extern int yyparse();
extern FILE *yyin;
extern FILE *yyout;
yylineno=1;
/*Definitions*/
#line 615 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 "test.l"


#line 769 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 337 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 513 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "test.l"
{return INCLUDE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "test.l"
{return HFSTD;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 "test.l"
{return HFSTR;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "test.l"
{return HFMATH;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 30 "test.l"
{return HFLIB;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "test.l"
{ return INT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "test.l"
{ return FLOAT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "test.l"
{ return CHAR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "test.l"
{ return STRING;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "test.l"
{return VOID;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 41 "test.l"
{return UDFUNC;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "test.l"
{return MAIN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "test.l"
{return PRINT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "test.l"
{return SCAN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "test.l"
{return RETURN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "test.l"
{return AT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "test.l"
{return FSINT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "test.l"
{return FSCRT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "test.l"
{return FSFLT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "test.l"
{return FSSRT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "test.l"
{return '[';}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "test.l"
{return ']';}        
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "test.l"
{return '{';}        
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "test.l"
{return '}';}       
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "test.l"
{return '(';}        
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "test.l"
{return ')';}    
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "test.l"
{return ',';}    
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "test.l"
{return EOI;}  
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "test.l"
{yylineno++;}      
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "test.l"
{ return ASSIGN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "test.l"
{ return '+'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "test.l"
{ return '-'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "test.l"
{ return '*'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "test.l"
{ return '/'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "test.l"
{ return '^'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "test.l"
{ return '%'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "test.l"
{ return EQ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "test.l"
{ return LT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "test.l"
{ return GT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "test.l"
{ return LTE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "test.l"
{ return GTE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "test.l"
{ return NE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 84 "test.l"
{ return ADD1; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 85 "test.l"
{ return SUB1; }   
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 86 "test.l"
{ return INCBY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 87 "test.l"
{ return DECBY; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "test.l"
{ return IF; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "test.l"
{ return ELSE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "test.l"
{ return ELIF;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 94 "test.l"
{ return SWITCH; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 95 "test.l"
{ return CASE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 96 "test.l"
{ return DEFAULT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 97 "test.l"
{ return BREAK;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 98 "test.l"
{ return COLON;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 101 "test.l"
{ return FOR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 102 "test.l"
{ return WHILE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 105 "test.l"
{return SIN;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 106 "test.l"
{return COS;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 107 "test.l"
{return TAN;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 108 "test.l"
{return LOG10;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 109 "test.l"
{return LOGE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 110 "test.l"
{return ODDEVEN;} 	      
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 111 "test.l"
{return FACT;} 	
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 114 "test.l"
{return SLCOM;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 115 "test.l"
{return MLCOM;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 "test.l"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 118 "test.l"
{yylval.ch = strdup(yytext);return STR;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "test.l"
{yylval.floating = atof(yytext); return DOUBLE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 122 "test.l"
{
	yylval.dim=atoi(yytext);
	return NUMBER;
	}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 127 "test.l"
{
		yylval.ch = strdup(yytext);
 		return VARIABLE;
 	 }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 133 "test.l"
ECHO;
	YY_BREAK
#line 1213 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 337 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 337 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 336);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 133 "test.l"


int yywrap() {
    return 1;
}

int main()
{
	yyin  = freopen("input.txt","r",stdin);
	yyout = freopen("output.txt","w",stdout);
	yyparse();
	
    return 0;
}